### ISSUE TITLE
S3 bucket

### ISSUE THREAD

**Issue by willwhite** [cutting-room-floor/glsl-optimizer#6]
It lIs is possible to consolidate this project's S3 bucket `s3://mapbox-glsl-optimizer` into the `s3://mapbox/mapbox-glsl-optimizer` bucket? I ask because buckets are a limited resource and consolidate would give us a little breathing room.

/cc @springmeyer @jfirebaugh

**Comment by springmeyer** [comment]
The bucked should likely be changed to `https://mapbox-node-binary.s3.amazonaws.com` to match all other node-pre-gyp published modules. However the discussion on chat yesterday I think concluded that this app is not longer needed, so we may just be able to delete it. I'll defer to @jfirebaugh on final decisions.

**Comment by jfirebaugh** [comment]
Looks like we switched to `mapbox-node-binary` back on the v0.1.1 release. I deleted the `mapbox-glsl-optimizer` bucket.
